

###
GET  https://losheroes-node-rest-api-prueba-production.up.railway.app/api/clients
###
POST  https://losheroes-node-rest-api-prueba-production.up.railway.app/api/clients
Content-Type: application/json

{
    "name":"jean",
    "rut":"123123113",
    "email":"jean2@gmail.com",
    "address":"las tarrias"
}

###
GET  https://losheroes-node-rest-api-prueba-production.up.railway.app/api/clients/1


###
PUT https://losheroes-node-rest-api-prueba-production.up.railway.app/api/clients/1
Content-Type: application/json
{
    "name":"jean",
    "rut":"44444",
    "email":"jean@gmail.com",
    "address":"las tarrias"
}

###
DELETE https://losheroes-node-rest-api-prueba-production.up.railway.app/api/clients/1